services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: chatbotapi
    ports:
      - "5046:5046"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=chatbotdb

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
  
volumes:
  mongo_data:

