services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: chatbotapi
    ports:
      - "5046:5046"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=chatbotdb

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Exponé el puerto si querés usarlo desde afuera
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: "ollama serve"

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - ollama  
  
volumes:
  mongo_data:
  ollama_data:
  n8n_data:
